# Generated by Django 3.2.3 on 2021-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='机场代码')),
                ('airport_name', models.CharField(max_length=20, unique=True, verbose_name='机场名称')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20, unique=True, verbose_name='航班号')),
                ('departure_day', models.DateField(verbose_name='出发日期')),
                ('departure_time', models.TimeField(verbose_name='出发时刻')),
                ('arrival_time', models.TimeField(verbose_name='到达时刻')),
                ('departure_airport', models.CharField(max_length=20, verbose_name='出发机场')),
                ('arrival_airport', models.CharField(max_length=20, verbose_name='到达机场')),
                ('stopover_airport', models.CharField(max_length=20, verbose_name='经停机场')),
                ('first_class_num', models.IntegerField(verbose_name='头等舱数')),
                ('first_class_price', models.IntegerField(verbose_name='头等舱价格')),
                ('economy_class_num', models.IntegerField(verbose_name='经济舱数')),
                ('economy_class_price', models.IntegerField(verbose_name='经济舱价格')),
                ('aircraft_type', models.CharField(blank=True, max_length=20, verbose_name='飞机型号')),
                ('voyage', models.IntegerField(blank='True', verbose_name='航程')),
                ('company', models.CharField(blank=True, max_length=40, verbose_name='航空公司')),
            ],
            options={
                'unique_together': {('flight_id', 'departure_day')},
            },
        ),
    ]
