# Generated by Django 3.2.3 on 2021-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idnum', models.CharField(max_length=40, unique=True, verbose_name='身份证号')),
                ('telnum', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.CharField(max_length=40, verbose_name='电子邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='乘机人姓名')),
                ('idnum', models.CharField(max_length=20, verbose_name='乘机人身份证号')),
                ('telnum', models.CharField(max_length=40, verbose_name='乘机人手机号')),
                ('user', models.ManyToManyField(to='FlightIndex.User')),
            ],
        ),
    ]
