# Generated by Django 3.2.3 on 2021-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightIndex', '0002_passenger_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='账号')),
                ('flightnum', models.CharField(max_length=20, verbose_name='航班号')),
                ('departure_day', models.DateField(verbose_name='出发日期')),
                ('passid', models.CharField(max_length=20, verbose_name='乘机人身份证号')),
                ('classtype', models.CharField(max_length=20, verbose_name='舱位')),
                ('ordertime', models.DateTimeField(verbose_name='订票时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, null=True, verbose_name='电子邮箱'),
        ),
    ]
